### ISSUE TITLE
.eth names only work sometimes (Firefox issue only) 

### ISSUE THREAD

**Issue by skunk-ink** [SkynetLabs/homescreen#14]
Sometimes when trying to add a ENS domain you receive a invalid skylink error. The only app I know to try is rift.eth so I cannot determine if it's rift or homescreen not working right sometimes. (Firefox only) 

1. Browse to your homescreen in Firefox
2. Add rift.eth to homescreen
3. If it works the first time, uninstall it and reinstall again using rift.eth

## Expected behavior
It should always be able to add rift.eth since it has worked a couple times. But sometimes it chooses not to accept the .eth address and produces a error saying it is an invalid address.

## Screenshots
https://siasky.net/XAFQdQs9xPKw0YIpSFcciolH2yAK7_v_TY0fQ_2ZGBvjQw

## Version Information (please complete the following information):
 
 - OS: Android, Windows
 - Browser: Firefox

**Comment by kwypchlo** [comment]
thank you for the report, I will be looking at this later this week

**Comment by kwypchlo** [comment]
.eth names should work better now - I have improved the .eth resolver service and added ipns support. 

I am going to close this issue but please let me know if the issue persists and we'll be debugging further.
