### ISSUE TITLE
My homescreen was overwritten and all dapps disappeared

### ISSUE THREAD

**Issue by ttonnfalt** [SkynetLabs/homescreen#51]
## Describe the bug
I was about to try out Danger's new widget in SkyOS and added it to my Homescreen. After adding it I noticed that all my dapps were gone.

## To Reproduce
Steps to reproduce are unclear.

## Expected behavior
Your dapps on your homescreen should **never** be overwritten and disappear.

## Screenshots
<img width="1350" alt="Skärmavbild 2021-10-20 kl  23 20 29" src="https://user-images.githubusercontent.com/78801143/138173928-0482f890-9286-4fe9-8dba-732ebee6681e.png">

## Version Information (please complete the following information):
 - OS: macOS 11.5.1
 - Browser Chrome 94.0.4606.81

## Additional context
Redsolver said it's _probably_ caused by this bug in `skynet-js`: https://github.com/SkynetLabs/skynet-js/pull/131
UserId: e453031a0a0d574bc58259e3d077f0ccc01f0f2bf1c4e7bcd1d868b2e8af7377

**Comment by TacoByte** [comment]
Happened to me too, very annoying and pretty scary bug

**Comment by ttonnfalt** [comment]
This happened to me today again
<img width="1340" alt="Skärmavbild 2021-11-13 kl  20 10 25" src="https://user-images.githubusercontent.com/78801143/141656568-10251c48-b5f2-4b87-aa5f-51a8b20e99c4.png">
